const mockArtists = [
    {
        id: '1',
        partyType: 'Person',
        fullName: 'Agostino Carracci',
        citedName: 'Carracci, Agostino',
        role: 'Unknown',
        nationality: 'Italian',
        birthDate: 'Unknown',
        deathDate: 'Unknown',
        birthPlace: 'Bologna, Italy',
        deathPlace: 'Unknown',
      },
      {
        id: '2',
        partyType: 'Person',
        fullName: 'Maribel Mamborini',
        citedName: 'Mambo Maribel',
        role: 'Unknown',
        nationality: 'Unknown',
        birthDate: 'Unknown',
        deathDate: 'Unknown',
        birthPlace: 'Unknown',
        deathPlace: 'Unknown',
      },
      {
        id: '3',
        partyType: 'Person',
        fullName: 'Tim Mossholder',
        citedName: 'Mossholder',
        role: 'Unknown',
        nationality: 'American',
        birthDate: 'Unknown',
        deathDate: 'Unknown',
        birthPlace: 'Unknown',
        deathPlace: 'Unknown',
      },
      {
        id: '4',
        partyType: 'Person',
        fullName: 'Sansibar Markedes',
        citedName: 'S.O.C.I.A.L.',
        role: 'Unknown',
        nationality: 'Unknown',
        birthDate: 'Unknown',
        deathDate: 'Unknown',
        birthPlace: 'Unknown',
        deathPlace: 'Unknown',
      },
      {
        id: '5',
        partyType: 'Unknown',
        fullName: "Unknown",
        citedName: 'Unknown',
        role: 'Unknown',
        nationality: 'French',
        birthDate: 'Unknown',
        deathDate: 'Unknown',
        birthPlace: 'Unknown',
        deathPlace: 'Unknown',
      },
      {
        id: '6',
        partyType: 'Person',
        fullName: 'George Ursachi',
        citedName: 'Sachi',
        role: 'Unknown',
        nationality: 'Romanian',
        birthDate: '2000-03-17',
        deathDate: 'Unknown',
        birthPlace: 'Bacau, Romania',
        deathPlace: 'Unknown',
      },
];

export default mockArtists;