const mockArtworks = [
  {
    id: '1',
    title: 'Retro metro',
    creationDate: '2012',
    medium: 'oil painting',
    description: null,
    dateSubmitted: '2022-06-04',
    itemWidth: 18.0,
    itemHeight: 24.0,
    itemDepth: 0.0,
    itemDiameter: 0.0,
    note: 'Lights shining in your eyes',
    tags: ['canvas', 'oil paints'],
    images: ['https://images.unsplash.com/photo-1541680670548-88e8cd23c0f4'],
    creator: [
      {
        id: '1',
        partyType: 'Person',
        fullName: 'Agostino Carracci',
        citedName: 'Carracci, Agostino',
        role: null,
        nationality: 'Italian',
        birthDate: null,
        deathDate: null,
        birthPlace: 'Bologna (Bologna province, Emilia-Romagna, Italy)',
        deathPlace: null,
      },
    ],
  },
  {
    id: '2',
    title: 'Vitamin Chaos',
    creationDate: '2015',
    medium: 'print',
    description: null,
    dateSubmitted: '2022-09-04',
    itemWidth: 22.0,
    itemHeight: 30.0,
    itemDepth: 0.0,
    itemDiameter: 0.0,
    note: 'Take ur viataminz',
    tags: ['print'],
    images: ['https://images.unsplash.com/photo-1618913001611-2054733f4aa8'],
    creator: [
      {
        id: '2',
        partyType: 'Person',
        fullName: 'Maribel Mamborini',
        citedName: 'Mambo Maribel',
        role: null,
        nationality: null,
        birthDate: null,
        deathDate: null,
        birthPlace: null,
        deathPlace: null,
      },
    ],
  },
  {
    id: '3',
    title: 'Spiked',
    creationDate: '1999',
    medium: 'acrylic on paper',
    description: null,
    dateSubmitted: '2022-09-01',
    itemWidth: 22.0,
    itemHeight: 30.0,
    itemDepth: 0.0,
    itemDiameter: 0.0,
    note: 'For Linda',
    tags: ['acrylic'],
    images: ['https://images.unsplash.com/photo-1590621819878-3fa04495626c'],
    creator: [
      {
        id: '3',
        partyType: 'Person',
        fullName: 'Tim Mossholder',
        citedName: 'Mossholder',
        role: null,
        nationality: 'American',
        birthDate: null,
        deathDate: null,
        birthPlace: null,
        deathPlace: null,
      },
    ],
  },
  {
    id: '4',
    title: 'Vehicle',
    creationDate: '2000',
    medium: 'acrylic on paper',
    description: null,
    dateSubmitted: '2022-09-01',
    itemWidth: 35.0,
    itemHeight: 22.0,
    itemDepth: 4.0,
    itemDiameter: 0.0,
    note: 'Note is a short sentence from the artist about the artwork, if relevant',
    tags: ['acrylic'],
    images: ['https://images.unsplash.com/photo-1590622974113-66a9160acf20'],
    creator: [
      {
        id: '3',
        partyType: 'Person',
        fullName: 'Tim Mossholder',
        citedName: 'Mossholder',
        role: null,
        nationality: 'American',
        birthDate: '1983-02-14',
        deathDate: null,
        birthPlace: 'Providence, Rhode Island',
        deathPlace: null,
      },
    ],
  },
  {
    id: '5',
    title: 'Losing the grip',
    creationDate: '2022',
    medium: 'acrylic on paper',
    description:
      'Thus one feels when losing their grip on reality. Strawberries are not real!',
    dateSubmitted: '2022-08-22',
    itemWidth: 22.0,
    itemHeight: 40.0,
    itemDepth: 3.0,
    itemDiameter: 0.0,
    note: null,
    tags: ['acrylic'],
    images: ['https://images.unsplash.com/photo-1533122250115-6bb28e9a48c3'],
    creator: [
      {
        id: '4',
        partyType: 'Person',
        fullName: 'Sansibar Markedes',
        citedName: 'S.O.C.I.A.L.',
        role: null,
        nationality: null,
        birthDate: null,
        deathDate: null,
        birthPlace: null,
        deathPlace: null,
      },
    ],
  },
  {
    id: '6',
    title: 'Untitled',
    creationDate: '2019',
    medium: 'acrylic on paper',
    description: null,
    dateSubmitted: '2022-08-22',
    itemWidth: 40.0,
    itemHeight: 15.0,
    itemDepth: 4.0,
    itemDiameter: 0.0,
    note: null,
    tags: ['acrylic'],
    images: ['https://images.unsplash.com/photo-1544277811-ce00cbaa4642'],
    creator: [
      {
        id: '4',
        partyType: 'Person',
        fullName: 'Sansibar Markedes',
        citedName: 'S.O.C.I.A.L.',
        role: null,
        nationality: null,
        birthDate: null,
        deathDate: null,
        birthPlace: null,
        deathPlace: null,
      },
    ],
  },
  {
    id: '7',
    title: 'Layers',
    creationDate: '2018',
    medium: 'digitally edited paper collage',
    description: 'Made with poster paper from the walls around the city',
    dateSubmitted: '2022-07-14',
    itemWidth: 40.0,
    itemHeight: 30.0,
    itemDepth: 2.0,
    itemDiameter: 0.0,
    note: 'Trash is art',
    tags: ['collage', 'trash'],
    images: ['https://images.unsplash.com/photo-1482160549825-59d1b23cb208'],
    creator: [
      {
        id: '5',
        partyType: null,
        fullName: null,
        citedName: null,
        role: null,
        nationality: 'French',
        birthDate: null,
        deathDate: null,
        birthPlace: null,
        deathPlace: null,
      },
    ],
  },
  {
    id: '8',
    title: 'Paths to the end',
    creationDate: '2021',
    medium: 'print',
    description: '',
    dateSubmitted: '2022-09-27',
    itemWidth: 40.0,
    itemHeight: 40.0,
    itemDepth: 2.0,
    itemDiameter: 0.0,
    note: 'All paths eventually lead to this end',
    tags: ['fractal', 'print', 'maths'],
    images: ['https://i.ibb.co/FJNw90c/paths-to-the-end.jpg'],
    creator: [
      {
        id: '6',
        partyType: 'Person',
        fullName: 'George Ursachi',
        citedName: 'Sachi',
        role: null,
        nationality: 'Romanian',
        birthDate: '2000-03-17',
        deathDate: null,
        birthPlace: 'Bacau, Romania',
        deathPlace: null,
      },
    ],
  },
  {
    id: '9',
    title: 'Plasmatic',
    creationDate: '2021',
    medium: 'print',
    description: '',
    dateSubmitted: '2022-09-27',
    itemWidth: 60.0,
    itemHeight: 40.0,
    itemDepth: 2.0,
    itemDiameter: 0.0,
    note: 'Romantic & plasmatic',
    tags: ['fractal', 'print', 'maths'],
    images: ['https://i.ibb.co/b7gVZ5B/Plasmatic.jpg'],
    creator: [
      {
        id: '6',
        partyType: 'Person',
        fullName: 'George Ursachi',
        citedName: 'Sachi',
        role: null,
        nationality: 'Romanian',
        birthDate: '2000-03-17',
        deathDate: null,
        birthPlace: 'Bacau, Romania',
        deathPlace: null,
      },
    ],
  },
  {
    id: '10',
    title: 'Sometimes I feel like this',
    creationDate: '2021',
    medium: 'print',
    description: '',
    dateSubmitted: '2022-09-27',
    itemWidth: 40.0,
    itemHeight: 40.0,
    itemDepth: 2.0,
    itemDiameter: 0.0,
    note: 'Have YOU ever felt like this?',
    tags: ['fractal', 'print', 'maths'],
    images: ['https://i.ibb.co/SPcpbmC/sometimes-i-feel-like-going-here.jpg'],
    creator: [
      {
        id: '6',
        partyType: 'Person',
        fullName: 'George Ursachi',
        citedName: 'Sachi',
        role: null,
        nationality: 'Romanian',
        birthDate: '2000-03-17',
        deathDate: null,
        birthPlace: 'Bacau, Romania',
        deathPlace: null,
      },
    ],
  },
]

/**
 * https://ibb.co/ftBpbnZ
https://ibb.co/CW5yZK7
https://ibb.co/wR71VQm
 */
export default mockArtworks
